"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class KiezboxMessage(google.protobuf.message.Message):
    """
    This message is used for
    KIEZBOX_CONTROL_APP PortNums.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Mode:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[KiezboxMessage._Mode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        maintenance: KiezboxMessage._Mode.ValueType  # 0
        normal: KiezboxMessage._Mode.ValueType  # 1
        emergency: KiezboxMessage._Mode.ValueType  # 2

    class Mode(_Mode, metaclass=_ModeEnumTypeWrapper):
        """Modes a kiezbox can be in"""

    maintenance: KiezboxMessage.Mode.ValueType  # 0
    normal: KiezboxMessage.Mode.ValueType  # 1
    emergency: KiezboxMessage.Mode.ValueType  # 2

    class _DeviceType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DeviceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[KiezboxMessage._DeviceType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        core: KiezboxMessage._DeviceType.ValueType  # 0
        """A core control module"""
        sensor: KiezboxMessage._DeviceType.ValueType  # 1
        """A dedicated sensor box"""
        display: KiezboxMessage._DeviceType.ValueType  # 2
        """A info dipslay"""
        button: KiezboxMessage._DeviceType.ValueType  # 3
        """The emergency button"""

    class DeviceType(_DeviceType, metaclass=_DeviceTypeEnumTypeWrapper):
        """Device Type of the kiezbox"""

    core: KiezboxMessage.DeviceType.ValueType  # 0
    """A core control module"""
    sensor: KiezboxMessage.DeviceType.ValueType  # 1
    """A dedicated sensor box"""
    display: KiezboxMessage.DeviceType.ValueType  # 2
    """A info dipslay"""
    button: KiezboxMessage.DeviceType.ValueType  # 3
    """The emergency button"""

    class _EmergencyType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _EmergencyTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[KiezboxMessage._EmergencyType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        medical: KiezboxMessage._EmergencyType.ValueType  # 0
        """Medical emergency"""
        fire: KiezboxMessage._EmergencyType.ValueType  # 1
        """Fire emergency"""
        crime: KiezboxMessage._EmergencyType.ValueType  # 2
        """Crime emergency"""
        sick: KiezboxMessage._EmergencyType.ValueType  # 3
        """Sick emergency"""
        help: KiezboxMessage._EmergencyType.ValueType  # 4
        """Help emergency"""

    class EmergencyType(_EmergencyType, metaclass=_EmergencyTypeEnumTypeWrapper): ...
    medical: KiezboxMessage.EmergencyType.ValueType  # 0
    """Medical emergency"""
    fire: KiezboxMessage.EmergencyType.ValueType  # 1
    """Fire emergency"""
    crime: KiezboxMessage.EmergencyType.ValueType  # 2
    """Crime emergency"""
    sick: KiezboxMessage.EmergencyType.ValueType  # 3
    """Sick emergency"""
    help: KiezboxMessage.EmergencyType.ValueType  # 4
    """Help emergency"""

    @typing.final
    class Meta(google.protobuf.message.Message):
        """Meta information identifying the box
        Also used as tags in the Database
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        BOX_ID_FIELD_NUMBER: builtins.int
        DIST_ID_FIELD_NUMBER: builtins.int
        SENS_ID_FIELD_NUMBER: builtins.int
        DEV_TYPE_FIELD_NUMBER: builtins.int
        box_id: builtins.int
        """ID if the Kiezbox
        only 8 bit used
        """
        dist_id: builtins.int
        """ID of the district the box is assigned to
        only 8 bit used
        """
        sens_id: builtins.int
        """ID of the sensor if this is a sensor module"""
        dev_type: global___KiezboxMessage.DeviceType.ValueType
        """Which type of device the controller should be"""
        def __init__(
            self,
            *,
            box_id: builtins.int | None = ...,
            dist_id: builtins.int | None = ...,
            sens_id: builtins.int | None = ...,
            dev_type: global___KiezboxMessage.DeviceType.ValueType | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_box_id", b"_box_id", "_dev_type", b"_dev_type", "_dist_id", b"_dist_id", "_sens_id", b"_sens_id", "box_id", b"box_id", "dev_type", b"dev_type", "dist_id", b"dist_id", "sens_id", b"sens_id"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_box_id", b"_box_id", "_dev_type", b"_dev_type", "_dist_id", b"_dist_id", "_sens_id", b"_sens_id", "box_id", b"box_id", "dev_type", b"dev_type", "dist_id", b"dist_id", "sens_id", b"sens_id"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_box_id", b"_box_id"]) -> typing.Literal["box_id"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_dev_type", b"_dev_type"]) -> typing.Literal["dev_type"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_dist_id", b"_dist_id"]) -> typing.Literal["dist_id"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_sens_id", b"_sens_id"]) -> typing.Literal["sens_id"] | None: ...

    @typing.final
    class Request(google.protobuf.message.Message):
        """Message to control one or multiple boxes"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _Type:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[KiezboxMessage.Request._Type.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            Update: KiezboxMessage.Request._Type.ValueType  # 0

        class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
        Update: KiezboxMessage.Request.Type.ValueType  # 0

        META_FIELD_NUMBER: builtins.int
        TYPE_FIELD_NUMBER: builtins.int
        type: global___KiezboxMessage.Request.Type.ValueType
        @property
        def meta(self) -> global___KiezboxMessage.Meta: ...
        def __init__(
            self,
            *,
            meta: global___KiezboxMessage.Meta | None = ...,
            type: global___KiezboxMessage.Request.Type.ValueType | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_type", b"_type", "meta", b"meta", "type", b"type"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_type", b"_type", "meta", b"meta", "type", b"type"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["_type", b"_type"]) -> typing.Literal["type"] | None: ...

    @typing.final
    class Control(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        MODE_FIELD_NUMBER: builtins.int
        UNIX_TIME_FIELD_NUMBER: builtins.int
        ROUTER_POWER_FIELD_NUMBER: builtins.int
        BOX_ID_FIELD_NUMBER: builtins.int
        DIST_ID_FIELD_NUMBER: builtins.int
        SENS_ID_FIELD_NUMBER: builtins.int
        STATUS_INTERVAL_FIELD_NUMBER: builtins.int
        mode: global___KiezboxMessage.Mode.ValueType
        unix_time: builtins.int
        router_power: builtins.bool
        box_id: builtins.int
        dist_id: builtins.int
        sens_id: builtins.int
        status_interval: builtins.int
        def __init__(
            self,
            *,
            mode: global___KiezboxMessage.Mode.ValueType = ...,
            unix_time: builtins.int = ...,
            router_power: builtins.bool = ...,
            box_id: builtins.int = ...,
            dist_id: builtins.int = ...,
            sens_id: builtins.int = ...,
            status_interval: builtins.int = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["box_id", b"box_id", "dist_id", b"dist_id", "mode", b"mode", "router_power", b"router_power", "sens_id", b"sens_id", "set", b"set", "status_interval", b"status_interval", "unix_time", b"unix_time"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["box_id", b"box_id", "dist_id", b"dist_id", "mode", b"mode", "router_power", b"router_power", "sens_id", b"sens_id", "set", b"set", "status_interval", b"status_interval", "unix_time", b"unix_time"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["set", b"set"]) -> typing.Literal["mode", "unix_time", "router_power", "box_id", "dist_id", "sens_id", "status_interval"] | None: ...

    @typing.final
    class Update(google.protobuf.message.Message):
        """Periodic update message containing optional core or sensor data"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        META_FIELD_NUMBER: builtins.int
        UNIX_TIME_FIELD_NUMBER: builtins.int
        CORE_FIELD_NUMBER: builtins.int
        SENSOR_FIELD_NUMBER: builtins.int
        unix_time: builtins.int
        """Unix timestamp ( in seconds ), when the measurements were taken"""
        @property
        def meta(self) -> global___KiezboxMessage.Meta: ...
        @property
        def core(self) -> global___KiezboxMessage.Core: ...
        @property
        def sensor(self) -> global___KiezboxMessage.Sensor: ...
        def __init__(
            self,
            *,
            meta: global___KiezboxMessage.Meta | None = ...,
            unix_time: builtins.int = ...,
            core: global___KiezboxMessage.Core | None = ...,
            sensor: global___KiezboxMessage.Sensor | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_core", b"_core", "_sensor", b"_sensor", "core", b"core", "meta", b"meta", "sensor", b"sensor"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_core", b"_core", "_sensor", b"_sensor", "core", b"core", "meta", b"meta", "sensor", b"sensor", "unix_time", b"unix_time"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_core", b"_core"]) -> typing.Literal["core"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_sensor", b"_sensor"]) -> typing.Literal["sensor"] | None: ...

    @typing.final
    class Core(google.protobuf.message.Message):
        """Contains general router status and internal sensor values"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        MODE_FIELD_NUMBER: builtins.int
        ROUTER_FIELD_NUMBER: builtins.int
        VALUES_FIELD_NUMBER: builtins.int
        mode: global___KiezboxMessage.Mode.ValueType
        @property
        def router(self) -> global___KiezboxMessage.Router: ...
        @property
        def values(self) -> global___KiezboxMessage.CoreValues: ...
        def __init__(
            self,
            *,
            mode: global___KiezboxMessage.Mode.ValueType = ...,
            router: global___KiezboxMessage.Router | None = ...,
            values: global___KiezboxMessage.CoreValues | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["router", b"router", "values", b"values"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["mode", b"mode", "router", b"router", "values", b"values"]) -> None: ...

    @typing.final
    class Router(google.protobuf.message.Message):
        """Router status information"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        POWERED_FIELD_NUMBER: builtins.int
        SW_VERSION_FIELD_NUMBER: builtins.int
        MODEL_FIELD_NUMBER: builtins.int
        powered: builtins.bool
        """True if power is supplied to the router"""
        sw_version: builtins.str
        """Router firmware software version
        For OpenWrt this would be VERSION="23.05.2"
        """
        model: builtins.str
        """Router model name"""
        def __init__(
            self,
            *,
            powered: builtins.bool = ...,
            sw_version: builtins.str | None = ...,
            model: builtins.str | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_model", b"_model", "_sw_version", b"_sw_version", "model", b"model", "sw_version", b"sw_version"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_model", b"_model", "_sw_version", b"_sw_version", "model", b"model", "powered", b"powered", "sw_version", b"sw_version"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_model", b"_model"]) -> typing.Literal["model"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_sw_version", b"_sw_version"]) -> typing.Literal["sw_version"] | None: ...

    @typing.final
    class CoreValues(google.protobuf.message.Message):
        """Sensor values measured at the core"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TEMP_OUT_FIELD_NUMBER: builtins.int
        TEMP_IN_FIELD_NUMBER: builtins.int
        HUMID_IN_FIELD_NUMBER: builtins.int
        SOLAR_VOLTAGE_FIELD_NUMBER: builtins.int
        SOLAR_POWER_FIELD_NUMBER: builtins.int
        SOLAR_ENERGY_DAY_FIELD_NUMBER: builtins.int
        SOLAR_ENERGY_TOTAL_FIELD_NUMBER: builtins.int
        BATTERY_VOLTAGE_FIELD_NUMBER: builtins.int
        BATTERY_CURRENT_FIELD_NUMBER: builtins.int
        TEMP_RTC_FIELD_NUMBER: builtins.int
        temp_out: builtins.int
        """Temperature outside (C)"""
        temp_in: builtins.int
        """Temperature inside (C)"""
        humid_in: builtins.int
        """Relative humidity inside (%)"""
        solar_voltage: builtins.int
        """Voltage of the solar panel (V)"""
        solar_power: builtins.int
        """Power output of the solar panel (W)"""
        solar_energy_day: builtins.int
        """Energy collected by the solar panel today (Wh)"""
        solar_energy_total: builtins.int
        """Energy collected by the solar panel in total (Wh)"""
        battery_voltage: builtins.int
        """Voltage of the (main) battery (V)"""
        battery_current: builtins.int
        """Current of the (main) battery (A)"""
        temp_rtc: builtins.int
        """Temperature of the realtime clock (C)"""
        def __init__(
            self,
            *,
            temp_out: builtins.int | None = ...,
            temp_in: builtins.int | None = ...,
            humid_in: builtins.int | None = ...,
            solar_voltage: builtins.int | None = ...,
            solar_power: builtins.int | None = ...,
            solar_energy_day: builtins.int | None = ...,
            solar_energy_total: builtins.int | None = ...,
            battery_voltage: builtins.int | None = ...,
            battery_current: builtins.int | None = ...,
            temp_rtc: builtins.int | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_battery_current", b"_battery_current", "_battery_voltage", b"_battery_voltage", "_humid_in", b"_humid_in", "_solar_energy_day", b"_solar_energy_day", "_solar_energy_total", b"_solar_energy_total", "_solar_power", b"_solar_power", "_solar_voltage", b"_solar_voltage", "_temp_in", b"_temp_in", "_temp_out", b"_temp_out", "_temp_rtc", b"_temp_rtc", "battery_current", b"battery_current", "battery_voltage", b"battery_voltage", "humid_in", b"humid_in", "solar_energy_day", b"solar_energy_day", "solar_energy_total", b"solar_energy_total", "solar_power", b"solar_power", "solar_voltage", b"solar_voltage", "temp_in", b"temp_in", "temp_out", b"temp_out", "temp_rtc", b"temp_rtc"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_battery_current", b"_battery_current", "_battery_voltage", b"_battery_voltage", "_humid_in", b"_humid_in", "_solar_energy_day", b"_solar_energy_day", "_solar_energy_total", b"_solar_energy_total", "_solar_power", b"_solar_power", "_solar_voltage", b"_solar_voltage", "_temp_in", b"_temp_in", "_temp_out", b"_temp_out", "_temp_rtc", b"_temp_rtc", "battery_current", b"battery_current", "battery_voltage", b"battery_voltage", "humid_in", b"humid_in", "solar_energy_day", b"solar_energy_day", "solar_energy_total", b"solar_energy_total", "solar_power", b"solar_power", "solar_voltage", b"solar_voltage", "temp_in", b"temp_in", "temp_out", b"temp_out", "temp_rtc", b"temp_rtc"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_battery_current", b"_battery_current"]) -> typing.Literal["battery_current"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_battery_voltage", b"_battery_voltage"]) -> typing.Literal["battery_voltage"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_humid_in", b"_humid_in"]) -> typing.Literal["humid_in"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_solar_energy_day", b"_solar_energy_day"]) -> typing.Literal["solar_energy_day"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_solar_energy_total", b"_solar_energy_total"]) -> typing.Literal["solar_energy_total"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_solar_power", b"_solar_power"]) -> typing.Literal["solar_power"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_solar_voltage", b"_solar_voltage"]) -> typing.Literal["solar_voltage"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_temp_in", b"_temp_in"]) -> typing.Literal["temp_in"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_temp_out", b"_temp_out"]) -> typing.Literal["temp_out"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_temp_rtc", b"_temp_rtc"]) -> typing.Literal["temp_rtc"] | None: ...

    @typing.final
    class Sensor(google.protobuf.message.Message):
        """Contains a set of sensor values and a sensor id"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        VALUES_FIELD_NUMBER: builtins.int
        @property
        def values(self) -> global___KiezboxMessage.SensorValues: ...
        def __init__(
            self,
            *,
            values: global___KiezboxMessage.SensorValues | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["values", b"values"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["values", b"values"]) -> None: ...

    @typing.final
    class SensorValues(google.protobuf.message.Message):
        """Sensor values measured at the sensor module"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TEMP_MAIN_FIELD_NUMBER: builtins.int
        HUMID_MAIN_FIELD_NUMBER: builtins.int
        PRESSURE_FIELD_NUMBER: builtins.int
        AIR_QUALITY_FIELD_NUMBER: builtins.int
        PART_PM25_FIELD_NUMBER: builtins.int
        PART_PM10_FIELD_NUMBER: builtins.int
        NOISE_FIELD_NUMBER: builtins.int
        TEMP_RTC_FIELD_NUMBER: builtins.int
        BATTERY_VOLTAGE_FIELD_NUMBER: builtins.int
        temp_main: builtins.int
        """[ BME Sensor ]
        Temperature (C)
        """
        humid_main: builtins.int
        """Humidity (%)"""
        pressure: builtins.int
        """Pressue (Pa)"""
        air_quality: builtins.int
        """Air Quality (??)"""
        part_pm25: builtins.int
        """Particles
        particles 1um (??)
        """
        part_pm10: builtins.int
        """particles 2.5um (??)"""
        noise: builtins.int
        """Noise (??)"""
        temp_rtc: builtins.int
        """Temperature of the rtc (C)"""
        battery_voltage: builtins.int
        """Voltage of the (main) battery (V)"""
        def __init__(
            self,
            *,
            temp_main: builtins.int | None = ...,
            humid_main: builtins.int | None = ...,
            pressure: builtins.int | None = ...,
            air_quality: builtins.int | None = ...,
            part_pm25: builtins.int | None = ...,
            part_pm10: builtins.int | None = ...,
            noise: builtins.int | None = ...,
            temp_rtc: builtins.int | None = ...,
            battery_voltage: builtins.int | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_air_quality", b"_air_quality", "_battery_voltage", b"_battery_voltage", "_humid_main", b"_humid_main", "_noise", b"_noise", "_part_pm10", b"_part_pm10", "_part_pm25", b"_part_pm25", "_pressure", b"_pressure", "_temp_main", b"_temp_main", "_temp_rtc", b"_temp_rtc", "air_quality", b"air_quality", "battery_voltage", b"battery_voltage", "humid_main", b"humid_main", "noise", b"noise", "part_pm10", b"part_pm10", "part_pm25", b"part_pm25", "pressure", b"pressure", "temp_main", b"temp_main", "temp_rtc", b"temp_rtc"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_air_quality", b"_air_quality", "_battery_voltage", b"_battery_voltage", "_humid_main", b"_humid_main", "_noise", b"_noise", "_part_pm10", b"_part_pm10", "_part_pm25", b"_part_pm25", "_pressure", b"_pressure", "_temp_main", b"_temp_main", "_temp_rtc", b"_temp_rtc", "air_quality", b"air_quality", "battery_voltage", b"battery_voltage", "humid_main", b"humid_main", "noise", b"noise", "part_pm10", b"part_pm10", "part_pm25", b"part_pm25", "pressure", b"pressure", "temp_main", b"temp_main", "temp_rtc", b"temp_rtc"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_air_quality", b"_air_quality"]) -> typing.Literal["air_quality"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_battery_voltage", b"_battery_voltage"]) -> typing.Literal["battery_voltage"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_humid_main", b"_humid_main"]) -> typing.Literal["humid_main"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_noise", b"_noise"]) -> typing.Literal["noise"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_part_pm10", b"_part_pm10"]) -> typing.Literal["part_pm10"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_part_pm25", b"_part_pm25"]) -> typing.Literal["part_pm25"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_pressure", b"_pressure"]) -> typing.Literal["pressure"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_temp_main", b"_temp_main"]) -> typing.Literal["temp_main"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_temp_rtc", b"_temp_rtc"]) -> typing.Literal["temp_rtc"] | None: ...

    @typing.final
    class Emergency(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TYPE_FIELD_NUMBER: builtins.int
        BUTTON_ID_FIELD_NUMBER: builtins.int
        UNIX_TIME_FIELD_NUMBER: builtins.int
        MESSAGE_FIELD_NUMBER: builtins.int
        type: global___KiezboxMessage.EmergencyType.ValueType
        """Type of the emergency"""
        button_id: builtins.int
        """ID of the button sending the emergency"""
        unix_time: builtins.int
        """Unix timestamp ( in seconds ), when the emergency happend"""
        message: builtins.str
        """Optional message describing what happened"""
        def __init__(
            self,
            *,
            type: global___KiezboxMessage.EmergencyType.ValueType = ...,
            button_id: builtins.int = ...,
            unix_time: builtins.int = ...,
            message: builtins.str | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_message", b"_message", "message", b"message"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_message", b"_message", "button_id", b"button_id", "message", b"message", "type", b"type", "unix_time", b"unix_time"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["_message", b"_message"]) -> typing.Literal["message"] | None: ...

    UPDATE_FIELD_NUMBER: builtins.int
    CONTROL_FIELD_NUMBER: builtins.int
    DISTRESS_FIELD_NUMBER: builtins.int
    @property
    def update(self) -> global___KiezboxMessage.Update: ...
    @property
    def control(self) -> global___KiezboxMessage.Control: ...
    @property
    def distress(self) -> global___KiezboxMessage.Emergency: ...
    def __init__(
        self,
        *,
        update: global___KiezboxMessage.Update | None = ...,
        control: global___KiezboxMessage.Control | None = ...,
        distress: global___KiezboxMessage.Emergency | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_control", b"_control", "_distress", b"_distress", "_update", b"_update", "control", b"control", "distress", b"distress", "update", b"update"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_control", b"_control", "_distress", b"_distress", "_update", b"_update", "control", b"control", "distress", b"distress", "update", b"update"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_control", b"_control"]) -> typing.Literal["control"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_distress", b"_distress"]) -> typing.Literal["distress"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_update", b"_update"]) -> typing.Literal["update"] | None: ...

global___KiezboxMessage = KiezboxMessage
